# App settings go here, they're validated in app.main.load_settings
dev:
  py_file: app/main.py
  static_path: static/
# this is the key used to encrypt cookies. Keep it safe!
# you can generate a new key with `base64.urlsafe_b64encode(os.urandom(32))`
cookie_secret_key: 'TMVnGYDCbNCWWPP4ihHIYP3zL44J-EszH4DVbXw68dE='
